name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version

    - name: install dependencies
      run: |
        yarn install

    - name: check source codes (linter)
      run: |
        yarn lint

    - name: build check
      run: |
        yarn build

    - name: test
      run: |
        yarn test
